module.exports = [
  {
    slug: 'cmdlwd',
    label: 'Education',
    name: 'CMD Leeuwarden',
    person: 'Gerald Kooistra',
    role: 'Communication & Multimedia Design, NHL Stenden',
    image: '/images/cmdlwd.png',
    url: 'https://cmdlwd.nl',
    urlLabel: 'cmdlwd.nl',
    quote: 'We needed something that felt like the programme — direct, open, built for students, not for management.',
    goal: 'Make prospective students feel what the programme is actually like, not just read about it.',
    surprise: 'He questioned things we took for granted. The navigation, the copy, the hierarchy. All of it better for it.',
  },
  {
    slug: 'tienskip',
    label: 'Teaching Democracy',
    name: 'Tienskip',
    person: 'Jeppe Kok',
    role: 'Democracy education for young adults',
    image: '/images/tienskip.jpg',
    url: 'https://tienskip.nl',
    urlLabel: 'tienskip.nl',
    quote: 'We needed something that felt like the programme itself — open, direct, not condescending to young people.',
    goal: 'Every agency we talked to wanted to make us look corporate. Tjerk actually listened to what we were trying to do.',
    surprise: 'He pushed back on our copy being too formal. Completely right, and the site is better for it.',
  },
  {
    slug: 'roelofschipper',
    label: 'Author portfolio',
    name: 'Roelof Schipper',
    person: 'Roelof Schipper',
    role: 'Author',
    image: '/images/roelof.png',
    url: 'https://roelofschipper.nl',
    urlLabel: 'roelofschipper.nl',
    quote: 'I just wanted a place for my books that didn\'t look like every other author site. He delivered exactly that.',
    goal: 'Minimal. Let the writing speak. Don\'t make it feel like a webshop.',
    surprise: 'Fast and honest. He told me what would work and what wouldn\'t. I didn\'t have to chase him.',
  },
  {
    slug: 'tentvanjos',
    label: 'Branding & web',
    name: 'Tent van Jos',
    person: 'Josytha Hakvoort',
    role: 'Small business identity',
    image: '/images/tentvanjos.jpg',
    url: 'https://tentvanjos.nl',
    urlLabel: 'tentvanjos.nl',
    quote: 'He made us look like ourselves online. That sounds simple but it really isn\'t.',
    goal: 'Small budget, tight timeline, no clear brief. Tjerk helped us figure out what we actually wanted before touching a single pixel.',
    surprise: 'People recognise us. We get messages from people who feel like they already know us before they\'ve met us.',
  },
  {
    slug: 'hamaki',
    label: 'Appointment app',
    name: 'Hamaki',
    person: null,
    role: 'Side project',
    image: '/images/hamaki.png',
    url: 'https://hamaki.pro',
    urlLabel: 'hamaki.pro',
    quote: 'A simple, no-nonsense appointment tool that gets out of your way.',
    goal: 'A lightweight appointment app for people who don\'t need the overhead of a big scheduling tool.',
    surprise: 'How much you can strip away and still have something genuinely useful.',
  },
  {
    slug: 'sprintcards',
    label: 'Design tool',
    name: 'Sprint.cards',
    person: null,
    role: 'Design Challenge Generator',
    image: '/images/sprintcards.png',
    url: 'https://sprint.cards',
    urlLabel: 'sprint.cards',
    quote: 'A random design challenge generator for when you\'re stuck or just want to play.',
    goal: 'A tool that generates design challenges on the fly — useful in workshops, classrooms, or when you need a creative kickstart.',
    surprise: 'Students use it outside of class. That wasn\'t planned, but it\'s the best possible outcome.',
  },
  {
    slug: 'wdtw',
    label: 'Festival',
    name: 'We Design the World',
    person: 'Gerald Kooistra',
    role: 'Design festival',
    image: '/images/wdtw.png',
    url: 'https://wdtw.nl',
    urlLabel: 'wdtw.nl',
    quote: 'A site that had to feel like the festival itself — bold, open, and a little chaotic.',
    goal: 'Get the energy of the festival into the browser. No corporate polish, just honest design for a design crowd.',
    surprise: 'How quickly Tjerk understood the tone. We barely had to explain it.',
  },
];
